import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Header } from "@components/layout";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "The Rick and Morty",
   description: "Generated by Rick and Morty app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Header />
            {children}
         </body>
      </html>
   );
}
